### ISSUE TITLE
Add representation of "MRM  Hotspot"

### ISSUE THREAD

**Issue by AMSP-04** [AMSP-04/NETN-MRM#2]
PCR # | Short Description | Module/Page | Problem/Proposal | TC/EC | Action | Note | Submitted by | Submission Date
-- | -- | -- | -- | -- | -- | -- | -- | --
COM_016 | Add representation of "MRM   Hotspot". | MRM | Add representation of a   geographical area that represents where disaggregation of units should take   place. | TC | Representation of Hotspot can be   used by MRM Trigger Federate to initiate disaggregation of units when   entering a specific geographical region and aggregation when leaving the   area. |   | Björn Löfstrand, bjornl@pitch.se | 2018-06-20

**Comment by lofstrandbjorn** [comment]
* Use NETN-SE regions to model hotspots. do not include in MRM module.
