### ISSUE TITLE
Complete MRM Documentation

### ISSUE THREAD

**Issue by lofstrandbjorn** [AMSP-04/NETN-MRM#6]

**Comment by lofstrandbjorn** [comment]
Complete rewrite to reflect major change.

**Comment by lofstrandbjorn** [comment]
* Complete rewrite of the NETN-MRM Documentation. The pattern has been simplified and extended with additional capabilities for controlling the Aggregate Unit state during federation execution.

**Comment by LennartOlsson** [comment]
The actions Divide and Merge needs some more thinking

**Comment by lofstrandbjorn** [comment]
A more complete description of all MRM tasks is now updated.
