### ISSUE TITLE
Change symbol description from APP6 (C) to (B)

### ISSUE THREAD

**Issue by martin-s** [AMSP-04/NETN-MRM#7]
https://github.com/AMSP-04/NETN-MRM/blob/433e3d6c5d0cd2d7a06570aa63d8984aa2e9887c/NETN-MRM.xml#L174

The description should mention APP6 (B) as the newer standards wouldn't follow the 15 character limit.

**Comment by lofstrandbjorn** [comment]
Resolved by using new URI based SymbolIdentifier.
