### ISSUE TITLE
Align interaction QuerySupportedCapabilities to NETN-ETR

### ISSUE THREAD

**Issue by martin-s** [AMSP-04/NETN-MRM#8]
https://github.com/AMSP-04/NETN-MRM/blob/433e3d6c5d0cd2d7a06570aa63d8984aa2e9887c/NETN-MRM.xml#L457

In ETR _QueryCapabilitiesSupported_ is used, whereas in MRM _QuerySupportedCapabilities_. Naming schema should be aligned between the two FOMs.

**Comment by lofstrandbjorn** [comment]
Aligned by changing NETN ETR interaction to QuerySupportedCapabilities
